services:
  - type: web
    name: discord-ticket-bot
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DISCORD_TOKEN
        scope: run
      - key: MONGODB_URI
        scope: run
      - key: WEBSITE_URL
        scope: run
      - key: NODE_ENV
        value: production
